### ISSUE TITLE
repr(C, align(...)) no longer working with bytemuck_derive 1.2.0

### ISSUE THREAD

**Issue by lassade** [Lokathor/bytemuck#129] opened 2022-08-16 22:34 UTC
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb57c04750b013fa16ae9b85c5fb8127

I'm currently using this as a workaround:

```toml
bytemuck = { version = "=1.10.0", features = ["derive"] }
bytemuck_derive = "=1.1.0" # necessary
```

**Comment by Lokathor** [comment] 2022-08-16 23:08
This is a duplicate of an issue from earlier today: https://github.com/Lokathor/bytemuck/issues/127

I just haven't yet had a chance to publish.

@lassade could you try building your code with the main branch in the git repo and confirm that it's working for you?

**Comment by lassade** [comment] 2022-08-17 01:18
Yes it did the trick!

**Comment by Lokathor** [comment] 2022-08-17 03:06
New versions released,

- bytemuck_derive-1.2.1
- byremuck-1.12.1

**Closed by Lokathor** 2022-08-17 03:06 UTC
