### ISSUE TITLE
Derive macro doesn't work when exported

### ISSUE THREAD

**Issue by crlf0710** [Lokathor/bytemuck#192] opened 2023-05-27 03:51 UTC
Currently if the derive macro is reexport in another crate, it doesn't work, because the crate using it won't have `::bytemuck` point to this crate.  `serde`'s solution is to provide an explicit `serde(crate = "...")` attribute. Maybe consider support it in the same way.

As a temporary workaround i'll add bytemuck dep to the usage site too. Might contribute if i've got time.

**Comment by notgull** [comment] 2023-05-27 04:01
Duplicate of #93

**Closed** 2023-05-27 04:02 UTC
